from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .abi import MAX_MESSAGE_BYTES, MAX_PAYLOAD_BYTES, PROTOCOL_VERSION, Schema

CPP_TYPES = {
    "bool": "bool",
    "i8": "std::int8_t",
    "u8": "std::uint8_t",
    "i16": "std::int16_t",
    "u16": "std::uint16_t",
    "i32": "std::int32_t",
    "u32": "std::uint32_t",
    "i64": "std::int64_t",
    "u64": "std::uint64_t",
    "f32": "float",
    "f64": "double",
}


def _dependencies(name: str, types: dict[str, dict[str, Any]]) -> set[str]:
    declaration = types[name]
    references: list[str]
    if declaration["kind"] == "array":
        references = [declaration["element"]]
    else:
        references = [field["type"] for field in declaration["fields"]]
    return {reference for reference in references if reference in types}


def _ordered_types(types: dict[str, dict[str, Any]]) -> list[str]:
    remaining = list(types)
    ordered: list[str] = []
    while remaining:
        ready = [name for name in remaining if _dependencies(name, types) <= set(ordered)]
        if not ready:
            raise ValueError("ABI type dependency graph cannot be ordered")
        for name in ready:
            ordered.append(name)
            remaining.remove(name)
    return ordered


def _cpp_type(type_name: str) -> str:
    return CPP_TYPES.get(type_name, type_name)


def _encode_lines(
    type_name: str,
    expression: str,
    types: dict[str, dict[str, Any]],
    *,
    indent: str,
    counter: list[int],
) -> list[str]:
    if type_name in CPP_TYPES:
        return [f"{indent}if (!writer.write_{type_name}({expression})) return false;"]
    declaration = types[type_name]
    if declaration["kind"] == "struct":
        lines: list[str] = []
        for field in declaration["fields"]:
            lines.extend(
                _encode_lines(
                    field["type"],
                    f"{expression}.{field['name']}",
                    types,
                    indent=indent,
                    counter=counter,
                )
            )
        return lines
    index = f"index_{counter[0]}"
    counter[0] += 1
    loop = f"for (std::size_t {index} = 0; {index} < {declaration['length']}; ++{index}) {{"
    lines = [indent + loop]
    lines.extend(
        _encode_lines(
            declaration["element"],
            f"{expression}[{index}]",
            types,
            indent=indent + "  ",
            counter=counter,
        )
    )
    lines.append(f"{indent}}}")
    return lines


def _decode_lines(
    type_name: str,
    expression: str,
    types: dict[str, dict[str, Any]],
    *,
    indent: str,
    counter: list[int],
) -> list[str]:
    if type_name in CPP_TYPES:
        return [f"{indent}if (!reader.read_{type_name}({expression})) return false;"]
    declaration = types[type_name]
    if declaration["kind"] == "struct":
        lines: list[str] = []
        for field in declaration["fields"]:
            lines.extend(
                _decode_lines(
                    field["type"],
                    f"{expression}.{field['name']}",
                    types,
                    indent=indent,
                    counter=counter,
                )
            )
        return lines
    index = f"index_{counter[0]}"
    counter[0] += 1
    loop = f"for (std::size_t {index} = 0; {index} < {declaration['length']}; ++{index}) {{"
    lines = [indent + loop]
    lines.extend(
        _decode_lines(
            declaration["element"],
            f"{expression}[{index}]",
            types,
            indent=indent + "  ",
            counter=counter,
        )
    )
    lines.append(f"{indent}}}")
    return lines


def generate_cpp_header(schema_path: Path) -> str:
    document = json.loads(schema_path.read_text(encoding="utf-8"))
    schema = Schema(document)
    ordered = _ordered_types(schema.types)
    lines = [
        "// Generated by qf abi generate. Do not edit manually.",
        "#pragma once",
        "",
        "#include <array>",
        "#include <cmath>",
        "#include <cstddef>",
        "#include <cstdint>",
        "#include <cstring>",
        "#include <limits>",
        "#include <type_traits>",
        "",
        "namespace qfabric::abi {",
        "",
        f"inline constexpr std::uint8_t kProtocolVersion = {PROTOCOL_VERSION};",
        "inline constexpr std::size_t kHeaderSize = 36;",
        f"inline constexpr std::size_t kMaxMessageBytes = {MAX_MESSAGE_BYTES};",
        f"inline constexpr std::size_t kMaxPayloadBytes = {MAX_PAYLOAD_BYTES};",
        "",
        "enum class MessageType : std::uint8_t { Request = 1, Response = 2 };",
        "enum class Effect : std::uint8_t {",
        "  Pure = 1, Idempotent = 2, Stateful = 3, Actuating = 4,",
        "};",
        "enum class Status : std::uint8_t {",
        "  Ok = 0, Malformed = 1, Oversized = 2, VersionMismatch = 3,",
        "  UnknownTask = 4, Stale = 5, Duplicate = 6, ExecutionError = 7,",
        "};",
        "inline constexpr Effect Q_PURE = Effect::Pure;",
        "inline constexpr Effect Q_IDEMPOTENT = Effect::Idempotent;",
        "inline constexpr Effect Q_STATEFUL = Effect::Stateful;",
        "inline constexpr Effect Q_ACTUATING = Effect::Actuating;",
        "constexpr bool canary_eligible(Effect effect) { return effect == Effect::Pure; }",
        "",
        "struct Metadata {",
        "  MessageType message_type = MessageType::Request;",
        "  Effect effect = Effect::Stateful;",
        "  Status status = Status::Ok;",
        "  std::uint32_t task_id = 0;",
        "  std::uint64_t invocation_id = 0;",
        "  std::uint32_t epoch = 0;",
        "  std::uint32_t contract_id = 0;",
        "  std::uint32_t relative_deadline_us = 0;",
        "};",
        "",
        "class Writer {",
        " public:",
        "  Writer(std::uint8_t* data, std::size_t capacity) : data_(data), capacity_(capacity) {}",
        "  std::size_t size() const { return offset_; }",
        "  Status status() const { return status_; }",
        "  bool write_bool(bool value) { return write_u8(value ? 1 : 0); }",
        "  bool write_i8(std::int8_t value) { return write_u8(static_cast<std::uint8_t>(value)); }",
        "  bool write_u8(std::uint8_t value) {",
        "    if (!reserve(1)) return false;",
        "    data_[offset_++] = value;",
        "    return true;",
        "  }",
        "  bool write_i16(std::int16_t value) {",
        "    return write_u16(static_cast<std::uint16_t>(value));",
        "  }",
        "  bool write_u16(std::uint16_t value) { return write_unsigned(value, 2); }",
        "  bool write_i32(std::int32_t value) {",
        "    return write_u32(static_cast<std::uint32_t>(value));",
        "  }",
        "  bool write_u32(std::uint32_t value) { return write_unsigned(value, 4); }",
        "  bool write_i64(std::int64_t value) {",
        "    return write_u64(static_cast<std::uint64_t>(value));",
        "  }",
        "  bool write_u64(std::uint64_t value) { return write_unsigned(value, 8); }",
        "  bool write_f32(float value) {",
        "    if (!std::isfinite(value)) return fail(Status::Malformed);",
        "    std::uint32_t bits = 0;",
        "    std::memcpy(&bits, &value, sizeof(bits));",
        "    return write_u32(bits);",
        "  }",
        "  bool write_f64(double value) {",
        "    if (!std::isfinite(value)) return fail(Status::Malformed);",
        "    std::uint64_t bits = 0;",
        "    std::memcpy(&bits, &value, sizeof(bits));",
        "    return write_u64(bits);",
        "  }",
        " private:",
        "  bool reserve(std::size_t amount) {",
        "    if (amount > capacity_ - offset_) return fail(Status::Oversized);",
        "    return true;",
        "  }",
        "  bool fail(Status status) { status_ = status; return false; }",
        "  template <typename T>",
        "  bool write_unsigned(T value, std::size_t width) {",
        "    if (!reserve(width)) return false;",
        "    for (std::size_t index = 0; index < width; ++index) {",
        "      const auto shift = static_cast<unsigned>((width - index - 1) * 8);",
        "      data_[offset_++] = static_cast<std::uint8_t>(value >> shift);",
        "    }",
        "    return true;",
        "  }",
        "  std::uint8_t* data_;",
        "  std::size_t capacity_;",
        "  std::size_t offset_ = 0;",
        "  Status status_ = Status::Ok;",
        "};",
        "",
        "class Reader {",
        " public:",
        "  Reader(const std::uint8_t* data, std::size_t size) : data_(data), size_(size) {}",
        "  std::size_t size() const { return offset_; }",
        "  bool read_bool(bool& value) {",
        "    std::uint8_t raw = 0;",
        "    if (!read_u8(raw) || raw > 1) return false;",
        "    value = raw == 1;",
        "    return true;",
        "  }",
        "  bool read_i8(std::int8_t& value) {",
        "    std::uint8_t raw = 0; if (!read_u8(raw)) return false;",
        "    value = static_cast<std::int8_t>(raw); return true;",
        "  }",
        "  bool read_u8(std::uint8_t& value) {",
        "    if (!reserve(1)) return false;",
        "    value = data_[offset_++];",
        "    return true;",
        "  }",
        "  bool read_i16(std::int16_t& value) {",
        "    std::uint16_t raw = 0; if (!read_u16(raw)) return false;",
        "    std::memcpy(&value, &raw, sizeof(value)); return true;",
        "  }",
        "  bool read_u16(std::uint16_t& value) { return read_unsigned(value, 2); }",
        "  bool read_i32(std::int32_t& value) {",
        "    std::uint32_t raw = 0; if (!read_u32(raw)) return false;",
        "    std::memcpy(&value, &raw, sizeof(value)); return true;",
        "  }",
        "  bool read_u32(std::uint32_t& value) { return read_unsigned(value, 4); }",
        "  bool read_i64(std::int64_t& value) {",
        "    std::uint64_t raw = 0; if (!read_u64(raw)) return false;",
        "    std::memcpy(&value, &raw, sizeof(value)); return true;",
        "  }",
        "  bool read_u64(std::uint64_t& value) { return read_unsigned(value, 8); }",
        "  bool read_f32(float& value) {",
        "    std::uint32_t bits = 0; if (!read_u32(bits)) return false;",
        "    std::memcpy(&value, &bits, sizeof(value)); return std::isfinite(value);",
        "  }",
        "  bool read_f64(double& value) {",
        "    std::uint64_t bits = 0; if (!read_u64(bits)) return false;",
        "    std::memcpy(&value, &bits, sizeof(value)); return std::isfinite(value);",
        "  }",
        " private:",
        "  bool reserve(std::size_t amount) const { return amount <= size_ - offset_; }",
        "  template <typename T>",
        "  bool read_unsigned(T& value, std::size_t width) {",
        "    if (!reserve(width)) return false;",
        "    value = 0;",
        "    for (std::size_t index = 0; index < width; ++index) {",
        "      value = static_cast<T>((value << 8) | data_[offset_++]);",
        "    }",
        "    return true;",
        "  }",
        "  const std::uint8_t* data_;",
        "  std::size_t size_;",
        "  std::size_t offset_ = 0;",
        "};",
        "",
        "static_assert(sizeof(float) == 4 && std::numeric_limits<float>::is_iec559);",
        "static_assert(sizeof(double) == 8 && std::numeric_limits<double>::is_iec559);",
        "",
        "inline Status encode_header(const Metadata& metadata, std::uint16_t payload_length,",
        "                            std::uint8_t* output, std::size_t capacity,",
        "                            std::size_t& written) {",
        "  if (payload_length > kMaxPayloadBytes) return Status::Oversized;",
        "  const auto message_type = static_cast<std::uint8_t>(metadata.message_type);",
        "  const auto effect = static_cast<std::uint8_t>(metadata.effect);",
        "  const auto status = static_cast<std::uint8_t>(metadata.status);",
        "  if (message_type < 1 || message_type > 2 || effect < 1 || effect > 4 || status > 7) {",
        "    return Status::Malformed;",
        "  }",
        "  if (metadata.message_type == MessageType::Request && metadata.status != Status::Ok) {",
        "    return Status::Malformed;",
        "  }",
        "  Writer writer(output, capacity);",
        "  if (!writer.write_u8('Q') || !writer.write_u8('F') || !writer.write_u8('A') ||",
        "      !writer.write_u8('B') || !writer.write_u8(kProtocolVersion) ||",
        "      !writer.write_u8(message_type) || !writer.write_u8(effect) ||",
        "      !writer.write_u8(status) || !writer.write_u32(metadata.task_id) ||",
        "      !writer.write_u64(metadata.invocation_id) || !writer.write_u32(metadata.epoch) ||",
        "      !writer.write_u32(metadata.contract_id) ||",
        "      !writer.write_u32(metadata.relative_deadline_us) ||",
        "      !writer.write_u16(payload_length) || !writer.write_u16(0)) {",
        "    return writer.status();",
        "  }",
        "  written = writer.size();",
        "  return written == kHeaderSize ? Status::Ok : Status::Malformed;",
        "}",
        "",
        "inline Status decode_header(const std::uint8_t* input, std::size_t size,",
        "                            Metadata& metadata, std::uint16_t& payload_length) {",
        "  if (size > kMaxMessageBytes) return Status::Oversized;",
        "  if (size < kHeaderSize) return Status::Malformed;",
        "  Reader reader(input, size);",
        "  std::uint8_t magic[4]{};",
        "  std::uint8_t version = 0;",
        "  std::uint8_t message_type = 0;",
        "  std::uint8_t effect = 0;",
        "  std::uint8_t status = 0;",
        "  std::uint16_t flags = 0;",
        "  if (!reader.read_u8(magic[0]) || !reader.read_u8(magic[1]) ||",
        "      !reader.read_u8(magic[2]) || !reader.read_u8(magic[3]) ||",
        "      !reader.read_u8(version) || !reader.read_u8(message_type) ||",
        "      !reader.read_u8(effect) || !reader.read_u8(status) ||",
        "      !reader.read_u32(metadata.task_id) ||",
        "      !reader.read_u64(metadata.invocation_id) || !reader.read_u32(metadata.epoch) ||",
        "      !reader.read_u32(metadata.contract_id) ||",
        "      !reader.read_u32(metadata.relative_deadline_us) ||",
        "      !reader.read_u16(payload_length) || !reader.read_u16(flags)) {",
        "    return Status::Malformed;",
        "  }",
        "  if (magic[0] != 'Q' || magic[1] != 'F' || magic[2] != 'A' || magic[3] != 'B') {",
        "    return Status::Malformed;",
        "  }",
        "  if (version != kProtocolVersion) return Status::VersionMismatch;",
        "  if (message_type < 1 || message_type > 2 || effect < 1 || effect > 4 || status > 7) {",
        "    return Status::Malformed;",
        "  }",
        "  metadata.message_type = static_cast<MessageType>(message_type);",
        "  metadata.effect = static_cast<Effect>(effect);",
        "  metadata.status = static_cast<Status>(status);",
        "  if (metadata.message_type == MessageType::Request && metadata.status != Status::Ok) {",
        "    return Status::Malformed;",
        "  }",
        "  if (flags != 0 || payload_length != size - kHeaderSize) return Status::Malformed;",
        "  return Status::Ok;",
        "}",
        "",
    ]

    for name in ordered:
        declaration = schema.types[name]
        if declaration["kind"] == "array":
            lines.append(
                f"using {name} = std::array<{_cpp_type(declaration['element'])}, "
                f"{declaration['length']}>;"
            )
        else:
            lines.append(f"struct {name} {{")
            for field in declaration["fields"]:
                lines.append(f"  {_cpp_type(field['type'])} {field['name']}{{}};")
            lines.append("};")
            lines.append(f"static_assert(std::is_standard_layout_v<{name}>);")
            lines.append(f"static_assert(std::is_trivially_copyable_v<{name}>);")
        lines.append("")

    for name in ordered:
        lines.append(f"inline bool encode_value(Writer& writer, const {name}& value) {{")
        lines.extend(
            _encode_lines(name, "value", schema.types, indent="  ", counter=[0])
        )
        lines.append("  return true;")
        lines.append("}")
        lines.append(f"inline bool decode_value(Reader& reader, {name}& value) {{")
        lines.extend(
            _decode_lines(name, "value", schema.types, indent="  ", counter=[0])
        )
        lines.append("  return true;")
        lines.append("}")
        lines.append("")

        size = schema.size_of(name)
        lines.extend(
            [
                f"inline Status encode_{name}(const {name}& value, std::uint8_t* output,",
                "                            std::size_t capacity, std::size_t& written) {",
                "  Writer writer(output, capacity);",
                "  if (!encode_value(writer, value)) return writer.status();",
                "  written = writer.size();",
                f"  return written == {size} ? Status::Ok : Status::Malformed;",
                "}",
                f"inline Status decode_{name}(const std::uint8_t* input, std::size_t size,",
                f"                            {name}& value) {{",
                f"  if (size != {size}) return Status::Malformed;",
                "  Reader reader(input, size);",
                "  if (!decode_value(reader, value) || reader.size() != size) {",
                "    return Status::Malformed;",
                "  }",
                "  return Status::Ok;",
                "}",
                "",
            ]
        )

    effect_names = {
        1: "Effect::Pure",
        2: "Effect::Idempotent",
        3: "Effect::Stateful",
        4: "Effect::Actuating",
    }
    for task in schema.tasks.values():
        pascal = "".join(part.capitalize() for part in task.name.split("_"))
        lines.extend(
            [
                f"inline constexpr std::uint32_t kTask{pascal} = {task.task_id};",
                f"inline constexpr Effect kTask{pascal}Effect = {effect_names[int(task.effect)]};",
            ]
        )

    lines.extend(["", "}  // namespace qfabric::abi", ""])
    return "\n".join(lines)


def write_cpp_header(header: str, output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(header, encoding="utf-8")
